# Generated by CodiumAI

import pytest
from backblaze_status.dev_debug import DevDebug


class TestDevDebug:

    #  Tags can be added to DevDebug using enable() and disable() methods
    def test_add_tags_in_disabled_mode(self):
        debug = DevDebug(enabled_mode=False)
        debug.enable("a")
        debug.enable("a.b")
        debug.disable("a.b.c")
        assert debug._tags == {"a", "a.b"}

    #  Tags can be added to DevDebug using enable() and disable() methods
    def test_add_tags_in_enabled_mode(self):
        debug = DevDebug(enabled_mode=True)
        debug.enable("a")
        debug.enable("a.b")
        debug.disable("a.b.c")
        assert debug._tags == {"a.b.c"}

    #  Tags can be added to DevDebug using enable() and disable() methods
    def test_enabled_default_mode(self):
        debug = DevDebug()
        assert debug.enabled_mode

    #  is_enabled() method returns True if a tag is enabled and False if it is disabled
    def test_is_enabled_in_enabled_mode(self):
        debug = DevDebug(enabled_mode=True)
        debug.enable("a")
        debug.enable("a.b")
        debug.disable("a.b.c")
        assert debug.is_enabled("a") == True
        assert debug.is_enabled("a.b") == True
        assert debug.is_enabled("a.b.c") == False

    #  is_enabled() method returns True if a tag is enabled and False if it is disabled
    def test_is_enabled_in_disabled_mode(self):
        debug = DevDebug(enabled_mode=False)
        debug.enable("a")
        debug.enable("a.b")
        debug.disable("a.b.c")
        assert debug.is_enabled("a") == True
        assert debug.is_enabled("a.b") == True
        assert debug.is_enabled("a.b.c") == False

    #  DevDebug can be initialized with both enabled_mode and disabled_mode as False
    def test_initialized_with_disabled_mode(self):
        debug = DevDebug(enabled_mode=False, disabled_mode=False)
        assert debug.enabled_mode == True
        assert debug.disabled_mode == False

    #  is_enabled() and is_disabled() methods return False for a tag that is not in the tags list
    def test_is_enabled_and_is_disabled(self):
        debug = DevDebug(enabled_mode=True)
        debug.enable("a")
        debug.enable("a.b")
        debug.disable("a.b.c")
        assert debug.is_enabled("x") == True
        assert debug.is_disabled("x") == False

    #  enable() and disable() methods can be called with '.' to enable or disable all tags
    def test_enable_and_disable_all_tags(self):
        debug = DevDebug(enabled_mode=True)
        debug.enable(".")
        assert debug.is_enabled("a") == True
        assert debug.is_enabled("a.b") == True
        assert debug.is_enabled("a.b.c") == True
        debug.disable(".")
        assert debug.is_disabled("a") == True
        assert debug.is_disabled("a.b") == True
        assert debug.is_disabled("a.b.c") == True
